spring.application.name=loginregister
spring.datasource.url=jdbc:mysql://localhost:3306/login_db
spring.datasource.username=root
spring.datasource.password=#Karan143

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
